version: '3'
services:
  envoy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 9901:9901
      - 10000:10000
    networks:
      - envoymesh
  echoapi:
    image: echoapi:latest
    ports:
      - 8888:8888
    networks:
      - envoymesh
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      envoymesh:
        aliases:
          - redis_server
  ratelimit:
    image: ratelimit:latest
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
    networks:
      - envoymesh
    volumes:
      - binary:/usr/local/bin/
      - ./examples:/data
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit

networks:
  envoymesh: {}

volumes:
  binary:
