---
domain: wikipedia
descriptors:
  - key: client-id
    descriptors:
      - key: class
        value: degenerates
        rate_limit:
          requests_per_unit: 1
          unit: second
      - key: class
        value: anonymous
        rate_limit:
          requests_per_unit: 0
          unit: second